<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.pansoft</groupId>
        <artifactId>osp-starter-parent</artifactId>
        <version>6.6.7400</version>
    </parent>
    <groupId>com.pansoft</groupId>
    <artifactId>osp-lcdp-app</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>osp-lcdp-app</name>
    <packaging>${my.packaging}</packaging>

    <scm>
        <connection>scm:git:${scm.url}</connection>
        <developerConnection>scm:git:${scm.url}</developerConnection>
        <url>${scm.url}</url>
        <tag>osp-demo-1.0.0</tag>
    </scm>

    <properties>
        <maven.compiler.encoding>UTF-8</maven.compiler.encoding>
        <!--maven命令打包时，传入参数.示例https://git.openserver.cn:8089/osp-low-code/osp-root-parent.git-->
        <scm.url/>
        <!--maven命令打包时，传入参数.示例maven-releases::default::http://maven.openserver.cn:8090/repository/maven-releases/-->
        <distribution.release.url/>
        <build.final.name>OSPApplication</build.final.name>
        <okhttp3.version>4.9.0</okhttp3.version>
    </properties>

    <dependencies>

        <dependency>
            <groupId>com.pansoft</groupId>
            <artifactId>osp-starter-auth</artifactId>
        </dependency>
        <dependency>
            <groupId>com.pansoft</groupId>
            <artifactId>osp-platform-base-file</artifactId>
        </dependency>
        <dependency>
            <groupId>com.pansoft</groupId>
            <artifactId>osp-platform-front-config</artifactId>
        </dependency>
        <dependency>
            <groupId>com.pansoft</groupId>
            <artifactId>osp-starter-log-db</artifactId>
        </dependency>
        <dependency>
            <groupId>com.pansoft</groupId>
            <artifactId>osp-starter-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.pansoft</groupId>
            <artifactId>osp-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.pansoft</groupId>
            <artifactId>osp-platform-develop</artifactId>
        </dependency>
        <dependency>
            <groupId>com.pansoft</groupId>
            <artifactId>osp-platform-metadata-manager</artifactId>
        </dependency>
        <dependency>
            <groupId>com.pansoft</groupId>
            <artifactId>osp-platform-form-manager</artifactId>
        </dependency>
        <dependency>
            <groupId>com.pansoft</groupId>
            <artifactId>osp-platform-service-manager</artifactId>
        </dependency>
        <dependency>
            <groupId>com.pansoft</groupId>
            <artifactId>osp-platform-bizmodel-manager</artifactId>
        </dependency>
        <dependency>
            <groupId>com.pansoft</groupId>
            <artifactId>osp-platform-bizmodel-convert</artifactId>
        </dependency>
        <dependency>
            <groupId>com.pansoft</groupId>
            <artifactId>osp-platform-mdm-manager</artifactId>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.pansoft</groupId>
            <artifactId>osp-platform-flow-builder</artifactId>
        </dependency>
        <dependency>
            <groupId>com.pansoft</groupId>
            <artifactId>osp-platform-portal</artifactId>
        </dependency>
        <dependency>
            <groupId>com.pansoft</groupId>
            <artifactId>osp-platform-flow-driver</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>
        <dependency>
            <groupId>com.pansoft</groupId>
            <artifactId>osp-starter-db-update</artifactId>
        </dependency>
        <dependency>
            <groupId>com.pansoft</groupId>
            <artifactId>osp-starter-cloud-config-zookeeper</artifactId>
        </dependency>
        <dependency>
            <groupId>com.pansoft</groupId>
            <artifactId>osp-platform-mobile-service</artifactId>
        </dependency>
        <dependency>
            <groupId>com.pansoft</groupId>
            <artifactId>osp-platform-flow-center</artifactId>
        </dependency>
        <dependency>
            <groupId>com.pansoft</groupId>
            <artifactId>osp-starter-cache-redis-jedis</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.7.11</version>
        </dependency>

        <dependency>
            <groupId>com.pansoft</groupId>
            <artifactId>osp-platform-minio-manager</artifactId>
            <!--            <version>6.6.76</version>-->
        </dependency>

    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>copy-webinf</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/${build.final.name}/WEB-INF</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>src/main/resources/WEB-INF</directory>
                                    <excludes>
                                        <exclude>lib/*</exclude>
                                    </excludes>
                                    <includes>
                                        <include>**/*</include>
                                    </includes>
                                    <filtering>false</filtering>
                                </resource>
                            </resources>
                            <encoding>UTF-8</encoding>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy-config</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/${build.final.name}/WEB-INF/classes
                            </outputDirectory>
                            <resources>
                                <resource>
                                    <directory>src/main/resources</directory>
                                    <includes>
                                        <include>**/*</include>
                                    </includes>
                                    <excludes>
                                        <exclude>WEB-INF/**</exclude>
                                    </excludes>
                                    <filtering>false</filtering>
                                </resource>
                            </resources>
                            <encoding>UTF-8</encoding>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <finalName>${build.final.name}</finalName>
    </build>
    <profiles>
        <profile>
            <id>jar</id>
            <properties>
                <my.packaging>jar</my.packaging>
            </properties>
            <activation>
                <property>
                    <name>my.packaging</name>
                    <value>jar</value>
                </property>
                <!-- 设置默认激活 -->
                <!--<activeByDefault>true</activeByDefault>-->
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-dependency-plugin</artifactId>
                        <version>3.1.2</version>
                        <executions>
                            <execution>
                                <id>copy-dependencies</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>copy-dependencies</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>${project.build.directory}/${build.final.name}/lib
                                    </outputDirectory>
                                    <excludeTransitive>false</excludeTransitive>
                                    <stripVersion>false</stripVersion>
                                    <overWriteReleases>false</overWriteReleases>
                                    <overWriteSnapshots>false</overWriteSnapshots>
                                    <overWriteIfNewer>true</overWriteIfNewer>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <!-- 可执行jar插件 -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-jar-plugin</artifactId>
                        <version>3.1.0</version>
                        <configuration>
                            <outputDirectory>${project.build.directory}/${build.final.name}/</outputDirectory>
                            <!--这些配置将写入到MANIFEST.MF文件中-->
                            <archive>
                                <!--指定程序入口-->
                                <manifest>
                                    <addClasspath>true</addClasspath>
                                    <classpathPrefix>lib</classpathPrefix>
                                    <mainClass>com.pansoft.lcdp.OSPApplication</mainClass>
                                </manifest>
                                <!-- (配置文件的外置目录) -->
                                <manifestEntries>
                                    <Class-Path>WEB-INF/classes/</Class-Path>
                                </manifestEntries>
                            </archive>
                            <includes>
                                <include>**/*.class</include>
                            </includes>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>war</id>
            <properties>
                <my.packaging>war</my.packaging>
            </properties>
            <activation>
                <property>
                    <name>my.packaging</name>
                    <value>war</value>
                </property>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-war-plugin</artifactId>
                        <version>3.1.0</version>
                        <configuration>
                            <packagingExcludes>
                                WEB-INF/classes/WEB-INF/**
                            </packagingExcludes>
                            <webResources>
                                <resource>
                                    <directory>src/main/resources/WEB-INF</directory>
                                    <targetPath>WEB-INF</targetPath>
                                    <filtering>false</filtering>
                                    <excludes>
                                        <exclude>lib/*</exclude>
                                    </excludes>
                                    <includes>
                                        <include>**/*</include>
                                    </includes>
                                </resource>
                            </webResources>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
