###############################################
# 第三方数据库连接池配置
# author wangxin
# version 2018.12.4
###############################################

# 初始化时建立物理连接的个数，并发量不大时，可以设置为3
# 初始化发生在显示调用init方法，或者第一次getConnection时
datasource.initialSize = 4

# 最小连接数，跟initialSize的值保持一致
datasource.minIdle = 4

# 最大连接数（根据数据库并发量设置最大连接数，还需要考虑集群节点个数）
datasource.maxActive = 300

# 获取连接超时时间（单位：ms）
datasource.maxWait = 5000

# 是否缓存preparedStatement，也就是PSCache。
#datasource.poolPreparedStatements = true
datasource.poolPreparedStatements = false

# 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
# maxOpenPreparedStatements是针对单个connection链接的
#datasource.maxOpenPreparedStatements = 100
datasource.maxOpenPreparedStatements = 0

# 连接有效性检测时间(单位:ms)
datasource.timeBetweenEvictionRunsMillis = 90000

# 获取连接检测，默认为关闭
datasource.testOnBorrow = false

# 归还连接检测，默认为关闭
datasource.testOnReturn = false

# 最小空闲时间(单位ms)，默认为30分钟
datasource.minEvictableIdleTimeMillis = 1800000

# 在获取连接后，确定是否要进行连接空间时间的检查
datasource.testWhileIdle = true
