##
#
# dubbo config by zangyanke at 2019-4-3
#
# 是否启用dubbo
dubbo.enable=false
# 当前应用的表示，osp平台中可以标示当前服务器的角色，需要和package.xml里面配置的<com.efounder.eai.EAIServer>的id对应

# <com.efounder.eai.EAIServer> 中配置protocol="dubbo" 标示调用该服务器通过dubbo协议，
# 启用dubbo协议后，host  port path  service 这些配置都无效，但是DataBaseName  DBNO 还有效
dubbo.applicationName=ospdemo
# dubbo注册中心配置 dubbo的注册中心可以是zookeeper redis nacos
dubbo.registryProtocol=zookeeper
# 例如
dubbo.registryAddress=127.0.0.1:2181
# dubbo的注册中心的用户和密码，如：zookeeper的用户 密码  redis的用户密码
dubbo.registryUsername=
dubbo.registryPassword=
# dubbo的监听端口
dubbo.protocolPort=21880
# 注册分组:不同应用可根据该属性区分,注册到zookeeper时,设置该项后,顶级目录为设置的值,这里为dubbo-pro,没有设置时,顶级目录为dubbo
# dubbo.registryGroup=dubbo-pro
# 最大线程数
dubbo.protocolThreads=500
# 超时时间
dubbo.referenceTimeout=60000
# 3.0 新增
#dubbo元数据中心配置
dubbo.metaDataCenterAddress=zookeeper://127.0.0.1:2181
dubbo.metaDataCenterUserName=
dubbo.metaDataCenterPassWord=
#dubbo配置中心
dubbo.configCenterAddress=zookeeper://127.0.0.1:2181
dubbo.configCenterUserName=
dubbo.configCenterPassWord=
#dubbo服务监听配置
dubbo.enableMetrics=true
dubbo.metricsPort=33880
dubbo.metricsProtocol=dubbo
# 是否简化注册中心,默认true
# dubbo.registrySimplified=false
# dubbo使用的协议,默认tri
# dubbo.protocolName=dubbo
#dubbo注册模式,all interface instance 默认为interface
#dubbo.registerMode=all