
###############################################
# 发送邮件配置
# author liliang
###############################################

## ssl.enable （No authentication mechanisms supported by both server and client）
# email.sslenable=true
## 发件邮箱服务器
#email.host=
##用户名
#email.user=
##密码
#email.password=
##发件人
#email.sender=


