###############################################
# 用于平台标准数据库的版本自动升级配置
# author xiewanzhi
# version 2018.8.1
###############################################
 
# 是否启用自动升级
flyway.enabled=false

# 启用自动升级的数据库ID,对应CnfgSpace/DBConfig.xml配置的ID
flyway.dbID=OSP_DB01

# 修改flyway.updateModule，按照自己的需求，引用相应的模块，以下是目前的所有模块，可选取其中一部分引用
# 其中meta,basic,service,model,form,permission,view必须要引用(meta必须放在第一个，view必须放在最后)。
# 对应关系如下
#1	元数据管理	meta
#2	基础	        basic
#3	认证	        auth
#4	定时任务	    timer
#5	主数据	    mdm
#6	开发平台	    develop
#7	数据同步	    mdmsync
#8	门户	        portal
#9	服务管理	    service
#10	模型管理	    model
#11	表单管理	    form
#12	影像管理	    image
#13	打印管理	    print
#14	流程管理	    flow
#15	附件管理	    affix
#16	权限管理	    permission
#17	微服务	    microservice
#18 视图        view
flyway.updateModule=meta,basic,auth,timer,mdm,develop,mdmsync,portal,service,model,form,image,print,flow,affix,permission,microservice,view