# access key
minio.accessKey=minioadmin
# secret access key
minio.secretAccessKey=minioadmin
# 存储对象的桶名称
minio.bucketName=hlzb
# 服务地址
minio.endpoint=http://192.168.30.193:9000
# 文件最大限制，字节数，例如 1024 (这项配置暂时没有用到，可以随便配一个)
#minio.maxSize=1024
# 是否使用HTTPS (true/false)
minio.secure=false