
###############################################
# 发送短信配置
# author baigh
###############################################

# mobilenote.type 短信平台类型（EMAY：亿美软通短信平台，ALIYUN：阿里云短信平台）
# mobilenote.type=

# mobilenote.softwareSerialNo=
# mobilenote.key=


