##redis setting
##author xiewz
##date 2017.10.24
#
##*****************jedis连接参数设置*********************#
#
##是否启用redis
#redis.enable=false
#
##运行模式：单机standalone、分片sharded、集群cluster三种模式#
#redis.runMode=standalone
#
##redis服务器配置，如果是集群，则使用英文逗号分隔
#redis.hostports=127.0.0.1:6379
##redis.hostports=
#
##*************JedisCluster构造函数的参数*****************#
##服务器密码，需要则设置登录密码
##redis.password=root
#
##连接超时时间
#redis.connectionTimeout=3000
#
##返回值的超时时间
#redis.soTimeout=3000
#
##出现异常最大重试次数
#redis.maxAttempts=10
#
##************************jedis池参数设置*******************#
#
##jedis的最大分配对象
#redis.maxTotal=300
#
##jedis最大保存idel状态对象数
#redis.maxIdle=50
#
##jedis最小保存idel状态对象数
#redis.minIdle=2
#
##jedis池没有对象返回时，最大等待时间
#redis.maxWaitMillis=1500
#
##jedis调用borrowObject方法时，是否进行有效检查
#redis.testOnBorrow=true
#
##jedis调用returnObject方法时，是否进行有效检查
#redis.testOnReturn=true