#SQL properties
#Mon Jan 05 07:15:24 UTC 2026
ServerScriptComp1=// (\u670D\u52A1\u7AEF\u811A\u672C\u7EC4\u4EF6)ServerScriptComp1.callFunction\r\nvar sql \= "1\=1"; \r\nvar queryValue \= PO.getValue("queryValue",null); \r\nif(queryValue \!\= null && queryValue \!\= ""){ \r\n    sql \= sql +" AND ( OTHER_MATERIAL_NAME LIKE '%'||@{queryValue}@||'%')"} \r\nPO.setParam("HLZB_tbOtherMaterial_MDMSelfWhere",sql);
