#SQL properties
#Tue Sep 09 08:58:43 UTC 2025
ServerScriptComp1=// (\u670D\u52A1\u7AEF\u811A\u672C\u7EC4\u4EF6)ServerScriptComp1.callFunction\nvar sql \= "1\=1"; \nvar queryValue \= PO.getValue("queryValue",null); \nif(queryValue \!\= null && queryValue \!\= ""){ \n    sql \= sql +" AND ( HLZB_CPBH  LIKE '%'||@{queryValue}@||'%' )"} \nPO.setParam("HLZB_CPBHGL_MDMSelfWhere",sql);
