#SQL properties
#Tue Sep 23 08:44:58 UTC 2025
ServerScriptComp1=// (\u670D\u52A1\u7AEF\u811A\u672C\u7EC4\u4EF6)ServerScriptComp1.callFunction\nvar sql \= "1\=1"; \r\nvar queryValue \= PO.getValue("queryValue",null); \r\nif(queryValue \!\= null && queryValue \!\= ""){ \r\n    sql \= sql +" AND ( CPXH_ID  LIKE '%'||@{queryValue}@||'%' OR CPXH_NAME LIKE '%'||@{queryValue}@||'%')"} \r\nPO.setParam("HLZB_PROD_CPXH_MDMSelfWhere",sql);
