#SQL properties
#Wed Aug 13 08:20:40 UTC 2025
ServerScriptComp1=// (\u670D\u52A1\u7AEF\u811A\u672C\u7EC4\u4EF6)ServerScriptComp1.callFunction\nvar sql\="1\=1";\nvar queryValue \= PO.getValue("queryValue",null);\nif(queryValue \!\= null && queryValue \!\= ""){\n    sql\=sql + "AND (F_GUID LIKE '%'||@{queryValue}@||'%' OR contract_no LIKE '%'||@{queryValue}@||'%')" // OR product_no LIKE '%'||@{queryValue}@||'%'\n}\nPO.setParam("HLZB_tbDelivery_MDMSelfWhere",sql );\n
