#SQL properties
#Wed Sep 24 08:09:53 UTC 2025
ServerScriptComp1=// (\u670D\u52A1\u7AEF\u811A\u672C\u7EC4\u4EF6)ServerScriptComp1.callFunction\r\nvar sql \= "1\=1"; \r\nvar queryValue \= PO.getValue("queryValue",null); \r\nif(queryValue \!\= null && queryValue \!\= ""){ \r\n    sql \= sql +" AND ( infoName LIKE '%'||@{queryValue}@||'%')"} \r\nPO.setParam("HLZB_tbDownstreamIndustry_MDMSelfWhere",sql);\r\nPO.setParam("HLZB_tbDownstreamIndustry_MDMSelfOrder","F_GUID DESC");
