#SQL properties
#Mon Aug 11 07:23:39 UTC 2025
ServerScriptComp1=// (\u670D\u52A1\u7AEF\u811A\u672C\u7EC4\u4EF6)ServerScriptComp1.callFunction\r\nvar sql \= "1\=1"; \r\nvar queryValue \= PO.getValue("queryValue",null); \r\nif(queryValue \!\= null && queryValue \!\= ""){ \r\n    sql \= sql +" AND ( F_GUID  LIKE '%'||@{queryValue}@||'%' OR contract_no LIKE '%'||@{queryValue}@||'%')"} \r\nPO.setParam("HLZB_tbHandover_MDMSelfWhere",sql);
