#SQL properties
#Tue Oct 14 00:34:06 UTC 2025
ServerScriptComp1=// (\u670D\u52A1\u7AEF\u811A\u672C\u7EC4\u4EF6)ServerScriptComp1.callFunction\nvar sql \= "1\=1"; \nvar CPXH_ID \= PO.getValue("CPXH_ID",null); \nif(CPXH_ID \!\= null && CPXH_ID \!\= ""){ \n    sql \= sql +" AND ( CPXH_ID  \= @{CPXH_ID}@)"} \nPO.setParam("HLZB_PROD_ZYCS_MDMSelfWhere",sql);\nPO.setParam("HLZB_PROD_ZYCS_MDMSelfOrder","F_XH ASC");
