#SQL properties
#Tue Jun 02 05:29:33 UTC 2026
ServerScriptComp1=// (\u670D\u52A1\u7AEF\u811A\u672C\u7EC4\u4EF6)ServerScriptComp1.callFunction\r\nvar sql \= "1\=1"; \r\nvar htbh \= PO.getValue("htbh",null); \r\nif(htbh \!\= null && htbh \!\= ""){ \r\n    sql \= sql +" AND ( htbh \= @{htbh}@)"} \r\n    else{\r\n         sql \= sql +" AND 1\=2"\r\n    }\r\nPO.setParam("HLZB_htmxb_MDMSelfWhere",sql);\r\n\r\n
