#SQL properties
#Mon Oct 13 03:44:29 UTC 2025
ServerScriptComp1=// (\u670D\u52A1\u7AEF\u811A\u672C\u7EC4\u4EF6)ServerScriptComp1.callFunction\nvar sql \= "1\=1"; \nvar CPXH_ID \= PO.getValue("CPLB_NAME",null); \nif(CPLB_PD \!\= null && CPLB_PD \!\= ""){ \n    sql \= sql +" AND ( CPXH_ID  \= @{CPXH_ID}@)"} \nPO.setParam("HLZB_PROD_ZYCS_MDMSelfWhere",sql);
